### ISSUE TITLE
How to put background on days that are holiday?

### ISSUE THREAD

**Issue by edsonrb2008** [kthornbloom/Monthly#51]

**Comment by richardtallent** [comment]
I've made a small update that adds a class to each date box in the form "dtYYYY-MM-DD". This would allow you to use your own CSS to format holidays in a special way.

For example, if you included the following CSS, this coming Christmas will be shown in pale green and will have a Christmas tree icon to the right of the day number:

```CSS
.dt2017-12-25 { background-color: #F0FFF0; }
.dt2017-12-25 .monthly-day-number:after { content: '\1F384'; }
```

Using CSS to style special dates directly is more flexible than having to, say, pass an array of holidays in the options. I debated having a variation of this class without the year, but only a few holidays (at least here in the States) are on the same date each year, so having the year allows maximum flexibility.
