### ISSUE TITLE
Weekend color number

### ISSUE THREAD

**Issue by tegarkurniawan** [kthornbloom/Monthly#54]

**Comment by richardtallent** [comment]
Hi @tegarkurniawan,

While day-of-week classes could be added to make this easier, you can already do this with plain CSS. For example, this code will change the background color of all Saturdays and Sundays to grey (assuming Sunday is the first day of the week in the settings):

```CSS
.monthly-week .m-d:nth-child(1),
.monthly-week .m-d:nth-child(7) {
    background-color: #e0e0e0;
}
```
